"""empty message

Revision ID: d3e1189b18b2
Revises: c33f555f6fca
Create Date: 2017-05-19 11:16:09.145319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e1189b18b2'
down_revision = 'c33f555f6fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'order')
    op.drop_column('user', 'date_modified')
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
